### ISSUE TITLE
CRAN Archived 2023-07-07

### ISSUE THREAD

**Issue by idblr** [michaeldorman/shadow#11]
I'm interested in using {shadow} and noticed v0.7.1 has been [archived](https://cran.r-project.org/package=shadow) by CRAN. Looks like the development version v0.7.2 addresses many (most?) of the [CRAN checks](https://cran-archive.r-project.org/web/checks/2023/2023-07-07_check_results_shadow.html). Any expectation to resubmit to CRAN? Thanks!

**Comment by michaeldorman** [comment]
Hi @idblr , thanks for your interest in `shadow`! Unfortunately, I don't have plans to work on it in the near future...
