### ISSUE TITLE
'obstacles' not in projected CRS <- for valid projection

### ISSUE THREAD

**Issue by grayrattus** [michaeldorman/shadow#2]
Hello,

First of all great work with this library. I followed all the examples and they are working great. The documentation is also really nice! :+1: 

I want to use your library for my custom `SpatialPolygonsDataFrame` but I run into some problems.

I was following https://journal.r-project.org/archive/2019/RJ-2019-024/RJ-2019-024.pdf
and for `build` data everything seems to work. The problem is when I define my own geometry.

Here is the piece of code I wrote.
```
library(shadow)
library(raster)
library(rgeos)
library(rgdal)
library(maptools)

# Building SpatialPolygonsDataFrame with some height
lat <- c(51.7586015,   51.7586172,   51.7586208,   51.7586015,   51.7586637,   51.7586999,   51.7587039,   51.7587059,   51.7587061,   51.758705,    51.7587264,  51.758732,   51.7587248,  51.7587223,  51.75872,    51.7587171,  51.7587265,  51.7587026,  51.7586944,  51.758697,   51.758847,   51.7588165,  51.7588112,  51.7588043,  51.7587903,  51.7586012,  51.7586015)
lon <- c(19.4561254 , 19.4563127 , 19.4563515 , 19.4561254, 19.4563245 , 19.4563162 , 19.4563132 , 19.456308 , 19.4563046 , 19.4562921 , 19.4562857 , 19.4563452 , 19.4563476 , 19.4563496 , 19.4563526 , 19.4563529 , 19.45645 , 19.4564577 , 19.4564766 , 19.4565474 , 19.4565136 , 19.4561084 , 19.45609 , 19.4560819 , 19.4560788 , 19.4561225 , 19.4561254) 
xym <- cbind(lat, lon)

p = Polygon(xym)
ps = Polygons(list(p),1)
sps = SpatialPolygons(list(ps))

proj4string(sps) = CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

data = data.frame(BLDG_HT=90)
spdf = SpatialPolygonsDataFrame(sps,data)

# calculate center of spdf
location = rgeos::gCentroid(spdf)
location_geo = spTransform(x = location, CRSobj = "+proj=longlat +datum=WGS84")

time = as.POSIXct("2004-12-24 13:30:00", tz = "UTC")

# calculating solar position for location
solar_pos = maptools::solarpos(location_geo, time)

footprint =
  shadowFootprint(
    obstacles = spdf,
    obstacles_height_field = "BLDG_HT",
    solar_pos = solar_pos,
    )

# Error in .checkObstacles(obstacles, obstacles_height_field) : 
#   'obstacles' not in projected CRS
# Calls: shadowFootprint -> shadowFootprint -> .local -> .checkObstacles
# Execution halted
```
I got shape from https://nominatim.openstreetmap.org/search.php?q=51.7586015%2C+19.4561254&polygon_geojson=1&viewbox= 

And when I try to plot it everthing seem to be fine with geometry.
![image](https://user-images.githubusercontent.com/19289505/75628111-2039a880-5bd6-11ea-927d-9a39b5939168.png)

I don't understand why I get error ` 'obstacles' not in projected CRS`. Is it something wrong in my `SpatialPolygonsDataFrame`?

**Comment by grayrattus** [comment]
Ok, it seems there were 2 problems:
1) I need to use `+proj=utm +zone=33 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,` unit + utm as projection.
2) The data I parsed from JS was corrupted.. 
```
lat <- c(51.7586015,   51.7586172,   51.7586208,  51.7586637,   51.7586999,   51.7587039,   51.7587059,   51.7587061,   51.758705,    51.7587264,  51.758732,   51.7587248,  51.7587223,  51.75872,    51.7587171,  51.7587265,  51.7587026,  51.7586944,  51.758697,   51.758847,   51.7588165,  51.7588112,  51.7588043,  51.7587903,  51.7586012,  51.7586015)
lon <- c(19.4561254 , 19.4563127 , 19.4563515 , 19.4563245 , 19.4563162 , 19.4563132 , 19.456308 , 19.4563046 , 19.4562921 , 19.4562857 , 19.4563452 , 19.4563476 , 19.4563496 , 19.4563526 , 19.4563529 , 19.45645 , 19.4564577 , 19.4564766 , 19.4565474 , 19.4565136 , 19.4561084 , 19.45609 , 19.4560819 , 19.4560788 , 19.4561225 , 19.4561254) 
```

**Comment by michaeldorman** [comment]
Hi,

Exactly, one of the points in the polygon was duplicated and there was a segment with zero area, and you need to use a projected CRS so that x, y and z axes are in the same units (meters). 

I modified the code of `shadowFootpring` to ignore duplicated points in the building outline, so at least this particular issue should not cause an error now.

Thanks for your interest in the package!
