### ISSUE TITLE
Consider terrain in shadow calculation

### ISSUE THREAD

**Issue by oiramkawon** [michaeldorman/shadow#6]
For shadow analysis it would be useful to consider the terrain around a building because this affects the size of the shadowed area. Also, it would be nice, if the algorithm takes into account the surrounding area, i.e. if there is a hill between the sun and the building.
Any plans to add this?

**Comment by michaeldorman** [comment]
Thanks for your interest in the package! Terrain is usually represented with a Digital Elevation Model (DEM) raster, which is quite different from the vector-based model in the `shadow` package. Purely raster-based shadow algorithms are widely available in other software, including in R package `insol` (https://cran.r-project.org/web/packages/insol/index.html). It could be possible to develop a hybrid approach, where obstacles such as buildings are represented with extruded polygons while terrain is taken to account using a DEM. However, this is well beyond the scope of the `shadow` package and there are no plans of implementing it, unfortunately.
