### ISSUE TITLE
Error using test code SPDF saying its spatial lines

### ISSUE THREAD

**Issue by Duk11** [michaeldorman/shadow#8]
Hello,
I keep running into the following error using both my own and your test datasets available in the package.

`Error in slot(x, "polygons") : 
  no slot of name "polygons" for this object of class "SpatialLines"
In addition: There were 50 or more warnings (use warnings() to see the first 50)`

Below is the code I tried for obtaining shadow footprint
```
library(shadow)
library(rgeos)
library(raster) 
build <- beersheva_build
location = gCentroid(build)
park = gBuffer(location, width = 12)

time2 = as.POSIXct(
   x = "2004-06-24 09:30:00",
   tz = "Asia/Jerusalem")
 solar_pos2 = solarpos2(location,time2)
 solar_pos2

 footprint = shadowFootprint(obstacles = build,
   obstacles_height_field = "height_m", solar_pos = solar_pos2)
```

**Comment by michaeldorman** [comment]
Hi, the `shadow` package was recently removed from CRAN due to uncorrected issues, which I don't have time to fix at the moment. Sorry for the inconvenience and thanks for your interest in the package!

**Comment by Duk11** [comment]
Hi,
Damn! Thanks for responding anyway! Do you know of a comparable package in R? I am trying to calculate and then visualise the shadow area projected by trees based on their height.
Many thanks,
Grace

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by michaeldorman** [comment]
You can check out the *Introduction* section in our paper from 2019 for an overview of existing packages:
https://journal.r-project.org/archive/2019/RJ-2019-024/RJ-2019-024.pdf
(I haven't been following up on newer developments, maybe there are newer packages that I'm not aware of.)
